apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app-deployment
  labels:
    app: welcome-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
        - name: welcome-app
          image: mohamed2200/welcome-app:v1
          ports:
            - containerPort: 3000
###
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: hello-node-service
#spec:
#  selector:
#    app: hello-node
#  ports:
   # - protocol: TCP
  #    port: 80
 #     targetPort: 3000
#  type: NodeService

###
