apiVersion: v1
kind: Service
metadata:
  name: welcome-app-service
  labels:
    app: welcome-app

spec:
  selector:
    app: welcome-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: nodejs
  type: NodePort
